version: "3.9"
services:
  instance1-zoo1:
    image: confluentinc/cp-zookeeper:latest
    hostname: instance1-zoo1
    container_name: instance1-zoo1
    ports:
      - "2181:2181"
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  instance1-kafka1:
    image: confluentinc/cp-kafka:latest
    hostname: instance1-kafka1
    container_name: instance1-kafka1
    ports:
      - "29092:29092"
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'instance1-zoo1:2181'
      ZOOKEEPER_SASL_ENABLED: 'false'
      
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT, EXTERNAL:SASL_PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://instance1-kafka1:9093, EXTERNAL://localhost:9092
      
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/configs/kafka_server_jaas.conf"
    depends_on:
      - instance1-zoo1
    volumes:
      - ./:/etc/kafka/configs
  